# ahhh yametteee><
LOCAL_PATH := $(call my-dir)

# Youtube
include $(CLEAR_VARS)
LOCAL_MODULE := Youtube
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Youtube.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
include $(BUILD_PREBUILT)
